@startuml c4_db_entity

title C4 - Database Entity Diagram

entity User {
  * **PK** user_id
  --
  Email VARCHAR
  Password_Hash VARCHAR
  Role ENUM('manager', 'staff', 'admin')
  Name TEXT
}

entity Task {
  * **PK** task_id
  --
  * **FK** Created_by User.user_id NULL
  --
  Title VARCHAR
  Description TEXT
  Status ENUM('todo', 'in_progress', 'done', 'review')
  Due_Date DATETIME NULL
  Updated_Date DATETIME NULL
}

entity Attachment {
  *PK attachment_id
  -- 
  file_name VARCHAR
  file_path VARCHAR
  uploaded_by FK User.user_id
  task_id FK Task.task_id
  upload_date DATETIME
}
Task ||--o{ Attachment : "has"
User ||--o{ Attachment : "uploads"

User ||--o{ Task : "creates"

@enduml